export default {
  "response": {
  "version":"0.1",
  "termsofService":"http://www.wunderground.com/weather/api/d/terms.html",
  "features": {
  "conditions": 1
  }
    }
  , "current_observation": {
        "image": {
        "url":"http://icons.wxug.com/graphics/wu2/logo_130x80.png",
        "title":"Weather Underground",
        "link":"http://www.wunderground.com"
        },
        "display_location": {
        "full":"Denver, CO",
        "city":"Denver",
        "state":"CO",
        "state_name":"Colorado",
        "country":"US",
        "country_iso3166":"US",
        "zip":"80201",
        "magic":"1",
        "wmo":"99999",
        "latitude":"39.74000168",
        "longitude":"-104.98000336",
        "elevation":"1598.1"
        },
        "observation_location": {
        "full":"Capitol Hill, Denver, Colorado",
        "city":"Capitol Hill, Denver",
        "state":"Colorado",
        "country":"US",
        "country_iso3166":"US",
        "latitude":"39.734711",
        "longitude":"-104.977921",
        "elevation":"5331 ft"
        },
        "estimated": {
        },
        "station_id":"KCODENVE218",
        "observation_time":"Last Updated on September 12, 3:14 PM MDT",
        "observation_time_rfc822":"Tue, 12 Sep 2017 15:14:40 -0600",
        "observation_epoch":"1505250880",
        "local_time_rfc822":"Tue, 12 Sep 2017 15:15:03 -0600",
        "local_epoch":"1505250903",
        "local_tz_short":"MDT",
        "local_tz_long":"America/Denver",
        "local_tz_offset":"-0600",
        "weather":"Clear",
        "temperature_string":"91.2 F (32.9 C)",
        "temp_f":91.2,
        "temp_c":32.9,
        "relative_humidity":"11%",
        "wind_string":"Calm",
        "wind_dir":"NNW",
        "wind_degrees":328,
        "wind_mph":0.0,
        "wind_gust_mph":0,
        "wind_kph":0,
        "wind_gust_kph":0,
        "pressure_mb":"1011",
        "pressure_in":"29.85",
        "pressure_trend":"-",
        "dewpoint_string":"30 F (-1 C)",
        "dewpoint_f":30,
        "dewpoint_c":-1,
        "heat_index_string":"87 F (31 C)",
        "heat_index_f":87,
        "heat_index_c":31,
        "windchill_string":"NA",
        "windchill_f":"NA",
        "windchill_c":"NA",
        "feelslike_string":"87 F (31 C)",
        "feelslike_f":"87",
        "feelslike_c":"31",
        "visibility_mi":"10.0",
        "visibility_km":"16.1",
        "solarradiation":"644",
        "UV":"2.0","precip_1hr_string":"0.00 in ( 0 mm)",
        "precip_1hr_in":"0.00",
        "precip_1hr_metric":" 0",
        "precip_today_string":"0.00 in (0 mm)",
        "precip_today_in":"0.00",
        "precip_today_metric":"0",
        "icon":"clear",
        "icon_url":"http://icons.wxug.com/i/c/k/clear.gif",
        "forecast_url":"http://www.wunderground.com/US/CO/Denver.html",
        "history_url":"http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KCODENVE218",
        "ob_url":"http://www.wunderground.com/cgi-bin/findweather/getForecast?query=39.734711,-104.977921",
        "nowcast":""
    }
}
